// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vm_host.proto

#include "vm_host.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace vm_manager {
}  // namespace vm_manager
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_vm_5fhost_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_vm_5fhost_2eproto = nullptr;
const uint32_t TableStruct_vm_5fhost_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_vm_5fhost_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rvm_host.proto\022\nvm_manager\032\014common.prot"
  "o2P\n\017StartupListener\022=\n\007VmReady\022\030.vm_man"
  "ager.EmptyMessage\032\030.vm_manager.EmptyMess"
  "ageb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_vm_5fhost_2eproto_deps[1] = {
  &::descriptor_table_common_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_vm_5fhost_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_vm_5fhost_2eproto = {
  false, false, 131, descriptor_table_protodef_vm_5fhost_2eproto, "vm_host.proto", 
  &descriptor_table_vm_5fhost_2eproto_once, descriptor_table_vm_5fhost_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_vm_5fhost_2eproto::offsets,
  nullptr, file_level_enum_descriptors_vm_5fhost_2eproto, file_level_service_descriptors_vm_5fhost_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_vm_5fhost_2eproto_getter() {
  return &descriptor_table_vm_5fhost_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_vm_5fhost_2eproto(&descriptor_table_vm_5fhost_2eproto);
namespace vm_manager {

// @@protoc_insertion_point(namespace_scope)
}  // namespace vm_manager
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
