// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vm_host.proto
// Original file comments:
//
// Copyright (c) 2022 Intel Corporation.
// All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//
#ifndef GRPC_vm_5fhost_2eproto__INCLUDED
#define GRPC_vm_5fhost_2eproto__INCLUDED

#include "vm_host.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vm_manager {

// The Startup Listener service definition.
class StartupListener final {
 public:
  static constexpr char const* service_full_name() {
    return "vm_manager.StartupListener";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Called by each VM when it starts up to indicate that it is ready to handle
    // incoming requests.
    virtual ::grpc::Status VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::vm_manager::EmptyMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vm_manager::EmptyMessage>> AsyncVmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vm_manager::EmptyMessage>>(AsyncVmReadyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vm_manager::EmptyMessage>> PrepareAsyncVmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vm_manager::EmptyMessage>>(PrepareAsyncVmReadyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Called by each VM when it starts up to indicate that it is ready to handle
      // incoming requests.
      virtual void VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vm_manager::EmptyMessage>* AsyncVmReadyRaw(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vm_manager::EmptyMessage>* PrepareAsyncVmReadyRaw(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::vm_manager::EmptyMessage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vm_manager::EmptyMessage>> AsyncVmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vm_manager::EmptyMessage>>(AsyncVmReadyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vm_manager::EmptyMessage>> PrepareAsyncVmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vm_manager::EmptyMessage>>(PrepareAsyncVmReadyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response, std::function<void(::grpc::Status)>) override;
      void VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vm_manager::EmptyMessage>* AsyncVmReadyRaw(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vm_manager::EmptyMessage>* PrepareAsyncVmReadyRaw(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_VmReady_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Called by each VM when it starts up to indicate that it is ready to handle
    // incoming requests.
    virtual ::grpc::Status VmReady(::grpc::ServerContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_VmReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_VmReady() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_VmReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VmReady(::grpc::ServerContext* /*context*/, const ::vm_manager::EmptyMessage* /*request*/, ::vm_manager::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVmReady(::grpc::ServerContext* context, ::vm_manager::EmptyMessage* request, ::grpc::ServerAsyncResponseWriter< ::vm_manager::EmptyMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_VmReady<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_VmReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_VmReady() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response) { return this->VmReady(context, request, response); }));}
    void SetMessageAllocatorFor_VmReady(
        ::grpc::MessageAllocator< ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_VmReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VmReady(::grpc::ServerContext* /*context*/, const ::vm_manager::EmptyMessage* /*request*/, ::vm_manager::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VmReady(
      ::grpc::CallbackServerContext* /*context*/, const ::vm_manager::EmptyMessage* /*request*/, ::vm_manager::EmptyMessage* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_VmReady<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_VmReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_VmReady() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_VmReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VmReady(::grpc::ServerContext* /*context*/, const ::vm_manager::EmptyMessage* /*request*/, ::vm_manager::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_VmReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_VmReady() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_VmReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VmReady(::grpc::ServerContext* /*context*/, const ::vm_manager::EmptyMessage* /*request*/, ::vm_manager::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVmReady(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_VmReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_VmReady() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->VmReady(context, request, response); }));
    }
    ~WithRawCallbackMethod_VmReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VmReady(::grpc::ServerContext* /*context*/, const ::vm_manager::EmptyMessage* /*request*/, ::vm_manager::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* VmReady(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VmReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_VmReady() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage>* streamer) {
                       return this->StreamedVmReady(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_VmReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VmReady(::grpc::ServerContext* /*context*/, const ::vm_manager::EmptyMessage* /*request*/, ::vm_manager::EmptyMessage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVmReady(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vm_manager::EmptyMessage,::vm_manager::EmptyMessage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_VmReady<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_VmReady<Service > StreamedService;
};

}  // namespace vm_manager


#endif  // GRPC_vm_5fhost_2eproto__INCLUDED
