// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vm_host.proto

#include "vm_host.pb.h"
#include "vm_host.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace vm_manager {

static const char* StartupListener_method_names[] = {
  "/vm_manager.StartupListener/VmReady",
};

std::unique_ptr< StartupListener::Stub> StartupListener::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StartupListener::Stub> stub(new StartupListener::Stub(channel, options));
  return stub;
}

StartupListener::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_VmReady_(StartupListener_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StartupListener::Stub::VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::vm_manager::EmptyMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VmReady_, context, request, response);
}

void StartupListener::Stub::async::VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VmReady_, context, request, response, std::move(f));
}

void StartupListener::Stub::async::VmReady(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VmReady_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::vm_manager::EmptyMessage>* StartupListener::Stub::PrepareAsyncVmReadyRaw(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VmReady_, context, request);
}

::grpc::ClientAsyncResponseReader< ::vm_manager::EmptyMessage>* StartupListener::Stub::AsyncVmReadyRaw(::grpc::ClientContext* context, const ::vm_manager::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVmReadyRaw(context, request, cq);
  result->StartCall();
  return result;
}

StartupListener::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StartupListener_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StartupListener::Service, ::vm_manager::EmptyMessage, ::vm_manager::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StartupListener::Service* service,
             ::grpc::ServerContext* ctx,
             const ::vm_manager::EmptyMessage* req,
             ::vm_manager::EmptyMessage* resp) {
               return service->VmReady(ctx, req, resp);
             }, this)));
}

StartupListener::Service::~Service() {
}

::grpc::Status StartupListener::Service::VmReady(::grpc::ServerContext* context, const ::vm_manager::EmptyMessage* request, ::vm_manager::EmptyMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace vm_manager

